apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db # this label must match the label in template. This is to tell the deployment/replicaset which pods to manage
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres:13
        envFrom:
        - configMapRef:
            name: postgres-config   # pulls POSTGRES_DB + POSTGRES_USER
        - secretRef:
            name: postgres-secret   # pulls POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
        volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}
