apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:

      containers:
        - name: web
          image: hongming2003/cicd_project:latest
          ports:
            - containerPort: 5000
            
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5   # Wait 5s after container starts
            periodSeconds: 10        # Then check /health every 10s

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10  # Wait 10s before first liveness check
            periodSeconds: 15        # Then check /health every 15s
