name: CI

on:
  push:
    branches: [ main ]
  pull_request:

env:
  ACTIONS_STEP_DEBUG: true

    
jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: List workspace files
        run: |
          ls -la

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint and Format Check
        run: |
          flake8 .
          black --check .
        continue-on-error: true

      - name: Run tests with coverage
        run: |
          coverage run -m unittest discover tests/unit_test
          coverage report -m

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: unit-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: List workspace files
        run: |
          ls -la

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKER_HUB_USERNAME }}/cicd_project:${{ github.sha }}


  integration-test:
    runs-on: ubuntu-latest
    needs: docker-build-and-push

    env:
      ACTIONS_STEP_DEBUG: true
      DB_HOST: ${{ vars.DB_HOST }}
      DB_NAME: ${{ vars.DB_NAME }}
      DB_USER: ${{ vars.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}


# Creating .env file for docker-compose because .env file is in .gitignore and won't be pushed to repo
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: List workspace files
        run: |
          ls -la

      - name: Generate .env from job env
        run: |
          echo "DB_HOST=$DB_HOST" >> .env
          echo "DB_NAME=$DB_NAME" >> .env
          echo "DB_USER=$DB_USER" >> .env
          echo "DB_PASSWORD=$DB_PASSWORD" >> .env
          
      - name: Start services with Docker Compose
      # Run docker compose in detached mode. Else, the job will be stuck here
        run: |
          docker compose up --build -d
      
      # # Debug: check running services
      # - name: Show running containers
      #   run: docker compose ps

      # # Debug: show DB logs
      # - name: Show DB logs
      #   run: docker compose logs db

      - name: Wait for Web to be healthy
        run: |
          echo "Waiting for web to be healthy..."
          timeout 60s bash -c 'until [ "$(docker inspect -f {{.State.Health.Status}} $(docker compose ps -q web))" = "healthy" ]; do sleep 2; done'
     
      - name: Wait for Postgres to be healthy

      # docker inspect -f {{.State.Health.Status}} - returns the health status of the container
      # $(docker compose ps -q db) - this get the container id of the db service

      # Anything inside $() gets executed first
      # timeout 90s limits the total execution time
      # bash -c '...' runs the command inside single quotes in a bash shell

        run: |
          echo "Waiting for db to be healthy..."
          docker compose ps
          timeout 90s bash -c 'until [ "$(docker inspect -f {{.State.Health.Status}} $(docker compose ps -q db))" = "healthy" ]; do sleep 2; done'

      # Integration test to be ran inside to the web container. Else the servvice host name does not exist
      - name: Run integration tests
        run: docker compose exec web python -m unittest discover -s tests/integration_test -p "*.py"
        
      - name: Tear down services
      # Ensure services are taken down even if the tests fail.continue-on-error
      # Tear down volumes too, so that the DB is re-initialized next time.This is important if it is a self-hosted runner.
        if: always()
        run: |
          docker compose down -v


  deploy:
    needs: integration-test
    runs-on: [self-hosted, windows, x64]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: List workspace files
        run: |
          dir 

      - name: Set up kubectl Configmaps
        run: |
          kubectl create configmap postgres-config --from-literal=POSTGRES_DB=${{ vars.DB_NAME }} --from-literal=POSTGRES_USER=${{ vars.DB_USER }} --dry-run=client -o yaml | kubectl apply -f -
          kubectl create secret generic postgres-secret --from-literal=POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }} --dry-run=client -o yaml | kubectl apply -f -
          kubectl describe configmap postgres-config

      - name: Set up kubectl secrets
        run: |
          kubectl create secret generic postgres-secret --from-literal=POSTGRES_PASSWORD=postgres --dry-run=client -o yaml | kubectl apply -f -
          kubectl describe secret postgres-secret

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f .\kubernetes\

      - name: Start port forward
        run: |
          $job = Start-Job { kubectl port-forward service/web 5000:5000 }

        # Stop-Job -Id $job.Id
        # Remove-Job -Id $job.Id

      # - name: Delete Configmaps and secrets
      #   if:always()
      #   run: |
      #     kubectl delete configmap postgres-config
      #     kubectl delete secret postgres-secret



      # - name: Delete deployment
      #   if:always()
      #   run: |
      #     kubectl delete -f .\kubernetes\
